[env:heltec_t190]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

board_build.flash_mode = dio
board_build.flash_size = 8MB
board_build.filesystem = littlefs

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
  adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
  adafruit/Adafruit GFX Library@^1.11.9
  jgromes/RadioLib@^6.6.0
  bblanchon/ArduinoJson@^7.2.0
